//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogonWEB.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            Publicacao = new HashSet<Publicacao>();
            Status = true;
            DataCadastro = DateTime.Now;
            DataUltAlteração = DateTime.Now;

        }

        public int Id_Usuario { get; set; }
        
        public string Nome { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório!!!")]
        public string Login { get; set; }
        [Required(ErrorMessage = "Campo Obrigatório!!!")]
        public string Senha { get; set; }
        public string Email { get; set; }
        public byte[] Imagem { get; set; }
        public bool Status { get; set; }

        public DateTime? DataCadastro { get; set; }
        
        public DateTime? DataUltAlteração { get; set; }
        public bool? UserAdmin { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImgUplView { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publicacao> Publicacao { get; set; }
    }
}
